# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
simcpp <- function(dt, l, mc) {
    invisible(.Call('_IMPACTncdIndonesia_simcpp', PACKAGE = 'IMPACTncdIndonesia', dt, l, mc))
}

simcpp_year_based <- function(dt, l, mc) {
    invisible(.Call('_IMPACTncdIndonesia_simcpp_year_based', PACKAGE = 'IMPACTncdIndonesia', dt, l, mc))
}

